### ISSUE TITLE
Pesquisa sobre arquitetura de software

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#10]
# Objetivo
Encontrar um material de descreva sobre arquitetura de software, capacitar toda equipe ser capaz de arquitetar um software.
Também pode ser elaborado um material de autoria do grupo para uma melhor explicação, caso não estejamos satisfeito com os materiais encontrados.

**Comment by ArthurGuilher62** [comment]
Resumo de arquitetura de software:
[arquitetura.md](https://github.com/user-attachments/files/17607085/arquitetura.md)
conteúdo retirado do site:
https://blog.infnet.com.br/arquitetura_software/como-fazer-projeto-de-arquitetura-de-software/
