### ISSUE TITLE
Pesquisa de Mercado

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#19]
# Objetivo
Elaborar uma pesquisa que descreva as funcionalidades de sistemas que se assemelham ao do nosso projeto, para que, com isso, possamos compreender como o nosso sistema pode ser organizado e quais outras funcionalidades podemos adicionar.

## Tarefas
- [x] Procurar por sistemas semelhantes
- [x] Elencar suas funcionalidades
- [x] Elencar funcionalidades que podemos adicionar ao nosso projeto
- [x] Registrar todas essas informações em um local que a equipe toda tenha acesso

**Comment by Ana-Luiza-SC** [comment]
Foi realizada uma pesquisa de mercado para analisar projetos com propostas similares ao nosso, em especial do site [ok.org.br](https://ok.org.br/projetos/):

[Pesquisa de Mercado.docx](https://github.com/user-attachments/files/17689391/Pesquisa.de.Mercado.docx)

[Pesquisa de Mercado.pdf](https://github.com/user-attachments/files/17689407/Pesquisa.de.Mercado.pdf)
