### ISSUE TITLE
Criação da Matriz de Competências.

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#2]
Esta issue tem como objetivo coordenar a criação da Matriz de Competências da equipe. A Matriz de Competências é uma ferramenta essencial para identificar as habilidades e conhecimentos disponíveis em tecnologias dentro da equipe, permitindo uma alocação mais eficiente de recursos e o desenvolvimento de estratégias de capacitação. O objetivo é desenvolver um formulário que permita a cada membro da equipe informar suas capacidades e habilidades em tecnologias específicas. O formulário deve ser projetado de maneira clara e abrangente, abordando as principais áreas de conhecimento relevantes para o projeto em questão.

**Comment by Ana-Luiza-SC** [comment]
Link de formulário para o avaliamento de conhecimentos prévios:

https://forms.office.com/Pages/ResponsePage.aspx?id=oZs17AtjK024M8jm1I-AWSoIDG-FzktFo4LDtRNI3hBURVpDQ1FNSTJEV0FINjRPQjRES1I1T1cwVS4u

**Comment by Ana-Luiza-SC** [comment]
Foi feita a documentação sobre os conhecimentos dos membros e quais tecnologias serão trabalhadas, disponível no aqruivo pdf:
[Capacitação Squad 6 - Documentos Google.pdf](https://github.com/user-attachments/files/17611606/Capacitacao.Squad.6.-.Documentos.Google.pdf)

e no link a seguir:
https://docs.google.com/document/d/1Yi_45_eemBBYRwSWMYzLBUSSnIZ0kHnIJvAlJzX2KuY/edit?usp=sharing
