### ISSUE TITLE
Treinamento em Figma

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#23]
# Objetivo
Conseguir fontes e materiais para capacitar o grupo todo em Figma para prototipação de telas, tanto de baixa fidelidade quanto de alta fidelidade.

**Comment by Neoprot** [comment]
Essa issue será levada para sprint 2

**Comment by TiagoTeixeira-2005** [comment]
Para aprendizado sobre o Figma, recomendamos um curso em vídeo gratuito do Chief of Design e um aulão para iniciantes do uiuxbr.design :
https://youtube.com/playlist?list=PLwgL9IEA0PxXzmOu0crRl9l6PT46nqtI9&si=gn1Sjz-Zwirqnt-U
https://youtu.be/1rXFpzQliA4?si=jOKmaDAFzggu3mFI
