### ISSUE TITLE
Pesquisa sobre UI e UX

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#24]
# Objetivo
Achar materiais e fontes que possam capacitar nossa equipe em UI e UX, visando uma melhor entrega visual de telas e uma melhor aparência a nossas telas

**Comment by NayraNery127** [comment]
[README.md](https://github.com/user-attachments/files/17641976/README.md)
É só um teste, não terminei

**Comment by Neoprot** [comment]
Se possível aprofundar mais sobre e tentar trazer oq seria elementos que tornam uma interface "bonita" e agradável

**Comment by NayraNery127** [comment]
[ui ux.docx](https://github.com/user-attachments/files/17707114/ui.ux.docx)
