### ISSUE TITLE
Treinamento para a API Querido Diário

### ISSUE THREAD

**Issue by Ana-Luiza-SC** [unb-mds/2024-2-Squad06#25]
Treinamento para a utilização da API Querido Diário e sobre as informações disponíveis nele sobre Belo Horizonte, MG.

**Comment by Neoprot** [comment]
Essa issue vai uma sprint pra frente

**Comment by alvesingrid** [comment]
[API meu querido diário.pdf](https://github.com/user-attachments/files/17780325/API.meu.querido.diario.pdf)
