### ISSUE TITLE
Pesquisa sobre padrão de projetos, organização de projetos

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#26]
# Objetivo
Pesquisar sobre os principais padrões de projetos e organização de pastas de projetos, visando uma melhor organização da equipe para começar a produção do projeto.

**Comment by alvesingrid** [comment]
Dois pontos principais para estruturar bem o projeto e facilitar a colaboração da equipe:
1. Padrões de Projetos (Design Patterns)
Esses padrões ajudam a resolver problemas recorrentes no desenvolvimento de software. Aqui estão alguns que podem ser úteis no contexto:
Principais Padrões de Projeto
	1.	Singleton
	•	Garante que uma classe tenha apenas uma instância e fornece um ponto global de acesso a ela.
	•	Útil para gerenciar estados compartilhados (como configurações do sistema ou conexão com API).
	2.	Factory Method
	•	Define uma interface para criar objetos, mas permite que subclasses alterem o tipo de objeto criado.
	•	Ideal para projetos que envolvem diferentes tipos de objetos com uma lógica comum.
	3.	Observer
	•	Define uma dependência “um-para-muitos”, de modo que, quando um objeto muda de estado, todos os dependentes são notificados.
	•	Excelente para atualizações em tempo real (como dashboards).
	4.	MVC (Model-View-Controller)
	•	Separa lógica de negócios, interface do usuário e controle da aplicação.
	•	Muito usado em projetos com interfaces web ou mobile.
	5.	Repository
	•	Abstrai a camada de acesso a dados, centralizando interações com o banco de dados.
	•	Melhora a testabilidade e organização da persistência.
Considerando um projeto de monitoramento de gastos públicos:
	•	É recomendado usar o MVC para organizar a interface e a lógica de negócios.
	•	Repository para organizar dados coletados da API Querido Diário.
	•	Usar o  Observer para lidar com atualizações automáticas de dados.
2. Organização de Pastas em Projetos
Uma boa organização de pastas ajuda na manutenção, escalabilidade e integração de equipes. Aqui está uma estrutura recomendada para projetos:
Estrutura Geral de Pastas
project/
│
├── src/                     # Código-fonte principal
│   ├── models/              # Modelos de dados (Entidades, Repositórios)
│   ├── controllers/         # Controladores da lógica de negócio
│   ├── services/            # Regras de negócio e integração de APIs
│   ├── views/               # Interfaces (web, APIs, etc.)
│   └── utils/               # Funções auxiliares
│
├── tests/                   # Testes automatizados
│   ├── unit/                # Testes unitários
│   ├── integration/         # Testes de integração
│   └── e2e/                 # Testes ponta a ponta
│
├── docs/                    # Documentação do projeto
│   ├── api/                 # Documentação de rotas e APIs
│   └── arquitetura.md       # Decisões arquiteturais e padrões usados
│
├── scripts/                 # Scripts auxiliares (migradores, jobs)
├── config/                  # Arquivos de configuração
├── data/                    # Dados locais (ex.: mocks, CSVs)
├── .env                     # Configurações sensíveis (credenciais)
├── requirements.txt         # Dependências (Python, por exemplo)
├── Dockerfile               # Configuração do contêiner Docker
└── README.md                # Introdução e guia do projeto
Por que essa organização é útil?
	•	Separação de responsabilidades: Facilita o trabalho em equipe, cada membro pode atuar em uma área específica.
	•	Facilidade de testes: Pastas separadas para testes promovem boa cobertura de código.
	•	Documentação clara: A pasta docs/ centraliza decisões e facilita o onboarding de novos membros.
Próximos Passos
	•	Definir os padrões de projeto que mais se alinham ao objetivo do seu projeto.
	•	Configurar a estrutura de pastas inicial e documentá-la no README.md.
	•	Criar templates ou guias para a equipe seguir (ex.: template de documentação, padrão de código).

**Comment by alvesingrid** [comment]
# Monitoramento de Gastos Públicos

## Descrição do Projeto
Este projeto tem como objetivo monitorar os gastos públicos utilizando dados coletados da API [Querido Diário](https://queridodiario.ok.org.br/). A aplicação permite identificar padrões de despesas, fornecedores recorrentes e possíveis irregularidades nas contas municipais, utilizando visualizações e dashboards interativos.

## Tecnologias Utilizadas
- **Python 3.10+**
- **Flask** (para o backend)
- **SQLAlchemy** (para o gerenciamento do banco de dados)
- **Requests** (para consumir a API Querido Diário)
- **Jinja2** (para templates HTML)
- **Bootstrap 5** (para estilização)
- **Docker** (para contêinerização)

---

## Padrões de Projeto Utilizados

### 1. **MVC (Model-View-Controller)**
- **Model**: Representa a estrutura de dados e a camada de persistência.
- **View**: Define a interface apresentada ao usuário (HTML, JSON, etc.).
- **Controller**: Gerencia a comunicação entre o Model e a View, orquestrando a lógica de negócios.

**Motivo**: O uso de MVC organiza o projeto, separando a lógica de negócios da interface e facilitando a manutenção.

### 2. **Repository**
- **Função**: Abstrai a camada de acesso a dados, centralizando interações com o banco de dados (queries, inserções, etc.).
  
**Motivo**: Torna o código mais testável e organizado, promovendo um desacoplamento entre a lógica de negócios e a persistência de dados.

### 3. **Observer**
- **Função**: Notifica automaticamente os componentes dependentes (como dashboards) quando houver atualizações nos dados de gastos.

**Motivo**: Facilita a implementação de atualizações em tempo real, melhorando a experiência do usuário.

---

## Estrutura de Pastas do Projeto

```plaintext
project/
│
├── src/                   # Código-fonte principal
│   ├── models/            # Modelos de dados (Entidades, Repositórios)
│   │   ├── base.py        # Classe base para os modelos
│   │   ├── expense.py     # Modelo de Gastos
│   │   └── repository.py  # Padrão Repository
│   │
│   ├── controllers/       # Controladores da lógica de negócio
│   │   ├── dashboard.py   # Controlador para visualizações
│   │   ├── expenses.py    # Controlador para operações de gastos
│   │   └── auth.py        # Controlador para autenticação
│   │
│   ├── services/          # Regras de negócio e integração de APIs
│   │   ├── api_service.py # Conexão com a API Querido Diário
│   │   └── notifier.py    # Implementação do padrão Observer
│   │
│   ├── views/             # Interfaces (Web, APIs)
│   │   ├── templates/     # Arquivos HTML
│   │   ├── static/        # Arquivos estáticos (CSS, JS)
│   │   └── routes.py      # Rotas do Flask
│   │
│   └── utils/             # Funções auxiliares
│       ├── logger.py      # Logs personalizados
│       └── validators.py  # Validação de dados
│
├── tests/                 # Testes automatizados
│   ├── unit/              # Testes unitários
│   ├── integration/       # Testes de integração
│   └── e2e/               # Testes ponta a ponta (End-to-End)
│
├── docs/                  # Documentação do projeto
│   ├── api/               # Documentação das rotas e APIs
│   └── arquitetura.md     # Decisões arquiteturais e padrões usados
│
├── scripts/               # Scripts auxiliares (migradores, jobs)
│   ├── data_import.py     # Script para importar dados
│   └── setup_db.py        # Script para inicializar o banco de dados
│
├── config/                # Arquivos de configuração
│   ├── settings.py        # Configurações gerais do sistema
│   ├── .env.example       # Exemplo de arquivo de configuração
│
├── data/                  # Dados locais (mocks, CSVs)
│   └── sample_data.csv    # Arquivo de exemplo de gastos
│
├── .env                   # Configurações sensíveis (credenciais)
├── requirements.txt       # Dependências do projeto
├── Dockerfile             # Configuração do contêiner Docker
├── docker-compose.yml     # Orquestração de contêineres
└── README.md              # Introdução e guia do projeto
```

---

## Como Executar o Projeto

### 1. Pré-requisitos
- **Python 3.10+**
- **Docker** (opcional)

### 2. Clonar o Repositório
```bash
git clone https://github.com/usuario/projeto-monitoramento-gastos.git
cd projeto-monitoramento-gastos
```

### 3. Configurar o Ambiente Virtual
```bash
python -m venv venv
source venv/bin/activate  # No Windows, use: venv\Scripts\activate
pip install -r requirements.txt
```

### 4. Configurar Variáveis de Ambiente
- Renomeie o arquivo `.env.example` para `.env` e preencha as credenciais necessárias.

### 5. Executar a Aplicação
```bash
python src/app.py
```

Acesse a aplicação em: [http://localhost:5000](http://localhost:5000)

### 6. Executar Testes
```bash
pytest
```

### 7. Utilizar Docker (Opcional)
```bash
docker-compose up --build
```

---

## Contribuição
1. Crie um fork do projeto.
2. Crie uma branch para sua feature (`git checkout -b feature/nova-feature`).
3. Commit suas mudanças (`git commit -m 'Adiciona nova feature'`).
4. Faça o push para a branch (`git push origin feature/nova-feature`).
5. Abra um Pull Request.

## Licença
Este projeto está sob a licença MIT. Veja o arquivo [LICENSE](LICENSE) para mais detalhes.

## Contato
Em caso de dúvidas ou sugestões, entre em contato pelo e-mail: exemplo@email.com
