### ISSUE TITLE
Documentação MVP

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#27]
# Objetivo
Visa a criação de um MVP 1 e 2 para a criação de um caminho claro para as features que devem estar na release 1 do nosso projeto.

**Comment by Ana-Luiza-SC** [comment]
Segue o link para a visualização da documentação do nosso MVP no Figma:

[Visualizar no Figma](https://www.figma.com/board/k1jEhT56FXr7OjXouwAhb1/MDS-SQUAD6?node-id=0-1&t=Ux3R8GxEJrYSn9mB-1)
