### ISSUE TITLE
Documentação User Stories

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#28]
# Objetivo
Criar as histórias de usuário para que possam ser alavancadas as principais features para o MVP.

**Comment by Ana-Luiza-SC** [comment]
Segue o link para a visualização da documentação User Stories no Figma:

[Visualizar no Figma](https://www.figma.com/board/k1jEhT56FXr7OjXouwAhb1/MDS-SQUAD6?node-id=0-1&t=Ux3R8GxEJrYSn9mB-1)
