### ISSUE TITLE
Criação de minis projetos usando React (Treinamento)

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#29]
# Objetivo
Alguns (entre 1 a 3) equipe deve criar um mini projeto utilizando react, visando uma capacitação da equipe toda no framework escolhido pela equipe.

# Critérios de aceitação 
- [ ] O projeto deve funcionar ;
- [ ] Cada projeto de cada membro deve estar em uma branch: `<usuario_git>/projeto_react`

# Tarefas
- [ ] Criar um pequeno projeto em React;
- [ ] Deixar nos comentários de forma clara como rodar o projeto, e também um mini resumo de como foi a experiência de usar react e qual dica daria a outra pessoa.

**Comment by TiagoTeixeira-2005** [comment]
Mini projeto de React: https://github.com/TiagoTeixeira-2005/projeto_react

**Comment by ArthurGuilher62** [comment]
Mini projeto React: https://github.com/ArthurGuilher62/projeto_react_A
