### ISSUE TITLE
Criação de minis projetos usando Django (Treinamento)

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#30]
# Objetivo
Alguns (entre 1 a 3) equipe deve criar um mini projeto utilizando Django, visando uma capacitação da equipe toda no framework escolhido pela equipe.

# Critérios de aceitação 
- [ ] O projeto deve funcionar ;
- [ ] Cada projeto de cada membro deve estar em uma branch: `<usuario_git>/projeto_django`

# Tarefas
- [ ] Criar um pequeno projeto em django;
- [ ] Deixar nos comentários de forma clara como rodar o projeto, e também um mini resumo de como foi a experiência de usar django e qual dica daria a outra pessoa.

**Comment by Neoprot** [comment]
Essa issue foi remanejada para a próxima sprint

**Comment by Ana-Luiza-SC** [comment]
Mini-projeto feito com Django: https://github.com/Ana-Luiza-SC/projeto_django
