### ISSUE TITLE
Implementação de um Miniprojeto de Extração de Dados de PDFs

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#33]
# Objetivo
Essa issue busca fazer testes com as principais bibliotecas de scrappers encontradas visando entender qual será a melhor para ser aplicada ao nosso projeto.

**Comment by Neoprot** [comment]
Essa issue ficou para uma outra sprint, ainda não temos certeza sobre qual sprint ela irá se na 3 ou 4

**Comment by alvesingrid** [comment]
[Uploading Etapas do Miniprojeto.pdf…]()

**Comment by alvesingrid** [comment]
[Uploading codigo em .py.pdf…]()
