### ISSUE TITLE
Definição do Scrum Master e do Product Owner

### ISSUE THREAD

**Issue by Ana-Luiza-SC** [unb-mds/2024-2-Squad06#37]
# Objetivo
Alocar as pessoas para os cargos de Scrum Master e Product Owner.

**Comment by Neoprot** [comment]
Após a reunião do dia 22/11 foi definido, tanto o Scrum Master, quanto o Product Owner.
Sendo eles Kauã Seichi (@Neoprot ), como Scrum master e Ana Luiza (@Ana-Luiza-SC), como Product Owner
