### ISSUE TITLE
Criação do protótipo no Figma

### ISSUE THREAD

**Issue by Ana-Luiza-SC** [unb-mds/2024-2-Squad06#42]
### **Descrição**  
Criação dos protótipos no Figma para avaliação e alinhamento do grupo.  

### **Objetivo**  
Desenvolver protótipos será essencial para validar as ideias do projeto, garantindo uma base visual sólida que facilite o entendimento do fluxo e a experiência do usuário.  
**Impacto esperado**:  
- Facilita o alinhamento entre os membros do time.  
- Ajuda a identificar possíveis melhorias antes da implementação.  
- Fornece uma visão clara do produto final, melhorando a experiência do usuário.  

### **Tarefas**  
- [x] Definir o layout inicial com base nos requisitos levantados.  
- [x] Criar protótipos para as principais telas/funções do sistema.  
- [x] Compartilhar os protótipos com o grupo para feedback.  
- [x] Realizar ajustes nos protótipos com base no feedback recebido.  
- [x] Realizar testes no protótipo para validar a navegabilidade e usabilidade.  

### **Critérios de Aceitação**  
- [x] Os protótipos refletem os requisitos levantados pelo grupo.  
- [x] As telas foram avaliadas e aprovadas por todos os membros.  
- [x] Os testes no protótipo confirmam que o fluxo de navegação está intuitivo.

**Comment by ArthurGuilher62** [comment]
link para protótipo do front end: https://www.figma.com/design/o8Yd8RRQcbLn2381ac2jOH/frontend?node-id=0-1&t=F0TwgAdWALWPl6XJ-1
