### ISSUE TITLE
Configuração de ambiente

### ISSUE THREAD

**Issue by Ana-Luiza-SC** [unb-mds/2024-2-Squad06#46]
## Objetivo
A criação da documentação de como subir ambiente do projeto.

## Tarefas
- [x] Identificar e instalar dependências necessárias.  
- [ ] Garantir que todas as bibliotecas e ferramentas estejam atualizadas.  
- [x] Configurar variáveis de ambiente e arquivos de configuração.  
- [x] Validar o funcionamento do ambiente local.  

## Critérios de Aceitação
- [x] Testar o ambiente para garantir compatibilidade com o projeto.  
- [x] Documentar o processo para facilitar reproduções futuras.

**Comment by Neoprot** [comment]
Essa issue foi concluida com a criação da branch dev, a criação do front foi feita utilizando principalmente o create-react-app da meta, inclusive tive alguns problemas com a criação e utilizei principalmente essa [issue](https://github.com/facebook/create-react-app/issues/13715) para resolver o front. Já o back foi feito na mão, utilizando django apenas para inicialização dos `apps` presentes no back,
