### ISSUE TITLE
Treinamento em Git

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#5]
## Objetivo
Capacitar a equipe no uso das ferramentas de milestone e issues do GitHub para otimizar a organização e o registro de atividades, aprimorando a comunicação e a colaboração entre os membros da equipe. O treinamento abordará conceitos básicos do Git e GitHub, criação e edição de issues e milestones, filtros e pesquisas, discussão e colaboração em issues, acompanhamento do progresso das milestones.

**Comment by Ana-Luiza-SC** [comment]
Curso gratuito da Fundação Getúlio Vargas de introdução ao Git e GitHub: 
https://educacao-executiva.fgv.br/cursos/online/curta-media-duracao-online/introducao-ao-git-e-github

**Comment by Neoprot** [comment]
Leitura sobre gitflow do blog da Alura:
https://www.alura.com.br/artigos/git-flow-o-que-e-como-quando-utilizar?srsltid=AfmBOorsSU8XBqqzgbL6NSi6NKB704f4rM272uWjQCnA_YG1tdTt7kqd

**Comment by Neoprot** [comment]
Na reunião do dia 28/10 foi feito uma conversa sobre o treinamento e junto chegamos a diversos links que podem ser úteis para os estudos do nossos integrantes. Ao longo da semana será feito acompanhamento dos integrantes para poder garantir que tudo foi compreendido.

**Comment by ArthurGuilher62** [comment]
comandos básicos para git: 
https://training.github.com/downloads/pt_BR/github-git-cheat-sheet.pdf

**Comment by Neoprot** [comment]
Para podermos ter uma melhor sincronia e também padrão de commits, segue um ótimo guia de contribuição que um grupo de MDS criou no semestre passado:
https://fga-eps-mds.github.io/2024.1-CALCULUS-DOC/guias/guia-contribuicao/

**Comment by Neoprot** [comment]
Caso você seja uma pessoa mais visual ou precisa de prática, temos também esse site para git:
https://learngitbranching.js.org
