### ISSUE TITLE
Pesquisa sobre Requisitos

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#7]
Essa issue tem como objetivo encontrar um material de descreva sobre requisitos de software, capacitar toda equipe para poder executar o papel de levantar requisitos.
Também pode ser elaborado um material de autoria do grupo para uma melhor explicação, caso não estejamos satisfeito com os materiais encontrados.

**Comment by TiagoTeixeira-2005** [comment]
Resumo sobre Requisitos de Software :
[Requisitos.pdf](https://github.com/user-attachments/files/17568075/Requisitos.pdf)
O conteúdo para esse resumo foi retirado do site:
https://softdesign.com.br/blog/requisitos-de-software-funcionais-e-nao-funcionais/
