### ISSUE TITLE
Treinamento de markdown

### ISSUE THREAD

**Issue by Neoprot** [unb-mds/2024-2-Squad06#8]
## Objetivo
Capacitar os integrantes do grupo em markdown, permitindo que todos consigam uma criar arquivos markdown funcionais, irá abordar todos os conceitos iniciais do markdown.

**Comment by Neoprot** [comment]
Olhando outras turmas da matéria tem o treinamento de markdown da turma do hilmer no projeto calculus:
https://fga-eps-mds.github.io/2024.1-CALCULUS-DOC/dojo/dojo-markdown/
Também pode usar o guia básico para escrever Markdown do github:
https://docs.github.com/pt/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github
Pode-se utilizar o site [markdown tutorial](https://www.markdowntutorial.com), que tem lições para fazer, porém é em inglês que pode ser uma barreira para o conhecimento.

**Comment by TiagoTeixeira-2005** [comment]
Um guia com as funções básicas do Markdown : 
[basic_markdown.md](https://github.com/user-attachments/files/17554263/basic_markdown.md)
